### ISSUE TITLE
To broke for your lesson on patron what best way to connect with ollama

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [severian42/Vodalus-Expert-LLM-Forge#2]
Love what I'm seeing but confused a little bit is there just easy way to use ollama I been trying to keep it using that for my model stash you know any help is appreciated once paid get course

**Comment by severian42** [comment]
No worries, happy to help! To use Ollama instead, you will need to adjust the base URL located in the llm_handler.py file to direct to the Ollama one (I believe the default is 11434) as well as input the exact model name from your ollama list into the OPENAI_MODEL field located in the params.py file. That should do it. You should be able to follow the Ollama FAQ guide from there if you need to run the server or something like that
